name: Auto Unzip File

on:
  push:
    branches:
      - main

jobs:
  unzip-process:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Ambil file dari repo kamu
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Proses Unzip dan Push menggunakan trik khusus (Abaikan Node.js Warning)
      - name: Ekstrak dan Simpan
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        run: |
          # Cari file zip, jika ada langsung ekstrak ke folder utama
          if [ -f "rizkyupdate.zip" ]; then
            echo "Menemukan rizkyupdate.zip, mengekstrak..."
            unzip -o rizkyupdate.zip -d .
            rm rizkyupdate.zip
          else
            echo "File rizkyupdate.zip tidak ditemukan di root folder."
          fi

          # Konfigurasi Bot Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Paksa simpan perubahan kembali ke GitHub
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto-unzip sukses [skip ci]"
            git push origin main
          else
            echo "Tidak ada perubahan baru."
          fi
